replicaCount: 1

image:
  repository: ""      
  pullPolicy: Always  
  tag: "latest"       

service:
  type: ClusterIP     
  port: 80         

resources:
  limits:           
    cpu: 300m
    memory: 256Mi
  requests:          
    cpu: 100m
    memory: 128Mi

livenessProbe:         # Vérifie si l'app est toujours en vie
  path: /              # ➤ Angular répond à la racine "/"
  port: 80

readinessProbe:        # Vérifie si l'app est prête à recevoir du trafic
  path: /
  port: 80