apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}        # ClusterIP, LoadBalancer ou NodePort
  ports:
    - port: {{ .Values.service.port }}    # Port du service
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "java-api.name" . }}  # Lie le service au bon pod