apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # Donne les droits groupe sur le PV monté
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
      # Init root (une seule fois) pour aligner ownership et permissions
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
          command: ["sh","-c"]
          args:
            - >
              set -eux;
              mkdir -p /usr/share/elasticsearch/data;
              chown -R 1000:1000 /usr/share/elasticsearch/data;
              chmod -R g+rwX /usr/share/elasticsearch/data
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=50s
              port: 9200
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 12
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3   # on cible la SC gp3 (ext4)
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi
