apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush            5
      Log_Level        info
      Parsers_File     parsers.conf
      storage.path     /var/fluent-bit/storage
      storage.metrics  On

    [INPUT]
      Name              tail
      Path              /var/log/containers/*.log
      Tag               kube.*
      Parser            cri
      Mem_Buf_Limit     128MB
      Skip_Long_Lines   On
      Refresh_Interval  5
      storage.type      filesystem

    [FILTER]
      Name                  kubernetes
      Match                 kube.*
      Kube_URL              https://kubernetes.default.svc:443
      Kube_Tag_Prefix       kube.var.log.containers.
      Merge_Log             On
      Merge_Log_Key         log
      Keep_Log              Off
      K8S-Logging.Parser    On
      K8S-Logging.Exclude   Off

    [OUTPUT]
      Name                es
      Match               *
      Host                elasticsearch.monitoring.svc.cluster.local
      Port                9200
      Logstash_Format     On
      Logstash_Prefix     fluent-synthetic
      Replace_Dots        On
      Retry_Limit         False
      Suppress_Type_Name  On
      Workers             1

  parsers.conf: |-
    [PARSER]
      Name        cri
      Format      regex
      Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - operator: Exists
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: cfg
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: state
              mountPath: /var/fluent-bit
      volumes:
        - name: cfg
          configMap:
            name: fluent-bit-config
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
              - key: parsers.conf
                path: parsers.conf
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: state
          hostPath:
            path: /var/fluent-bit
            type: DirectoryOrCreate
