apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.io/bitnami/elasticsearch:8.13.2
          ports:
            - { containerPort: 9200, name: http }
            - { containerPort: 9300, name: transport }
          env:
            - { name: discovery.type, value: single-node }
            # POC : pas d'auth/TLS pour éviter toute saisie d'identifiants
            - { name: ELASTICSEARCH_ENABLE_SECURITY, value: "no" }
            - { name: ES_JAVA_OPTS, value: "-Xms512m -Xmx512m" }
          resources:
            requests: { memory: "1Gi", cpu: "500m" }
            limits:   { memory: "2Gi", cpu: "1" }
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  selector:
    app: elasticsearch
  ports:
    - { protocol: TCP, port: 9200, targetPort: 9200, name: http }
    - { protocol: TCP, port: 9300, targetPort: 9300, name: transport }
