apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush           5
      Log_Level       info
      Parsers_File    parsers.conf
      Storage_Path    /buffers
      storage.metrics On

    [INPUT]
      Name              tail
      Path              /var/log/containers/*.log
      Tag               kube.*
      Parser            cri
      Mem_Buf_Limit     32MB
      Skip_Long_Lines   On
      Refresh_Interval  10
      storage.type      filesystem

    [FILTER]
      Name                  kubernetes
      Match                 kube.*
      Kube_URL              https://kubernetes.default.svc:443
      Kube_Tag_Prefix       kube.var.log.containers.
      Merge_Log             On
      Merge_Log_Key         log
      Keep_Log              Off
      K8S-Logging.Parser    On
      K8S-Logging.Exclude   Off

    [OUTPUT]
      Name                es
      Match               *
      Host                elasticsearch.monitoring.svc.cluster.local
      Port                9200
      Logstash_Format     On
      Logstash_Prefix     fluent-synthetic
      Replace_Dots        On
      Retry_Limit         False
      Suppress_Type_Name  On
      Workers             1

  parsers.conf: |-
    [PARSER]
      Name        cri
      Format      regex
      Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z

