# voir https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

apiVersion: apps/v1          # Type d'API Kubernetes utilisée (ici pour les Deployments)
kind: Deployment             # On déclare un "Deployment"
metadata:
  name: hello-springboot-deployment   # Nom du déploiement
  labels:
    app: hello-springboot             # Étiquette (utilisée pour faire le lien avec le Service)
spec:
  replicas: 1                         # Nombre d'instances de ton app
  selector:
    matchLabels:
      app: hello-springboot           # Sélection des pods via ce label
  template:                           # Modèle de pod à créer
    metadata:
      labels:
        app: hello-springboot
    spec:
      containers:
      - name: hello-springboot        # Nom du conteneur dans le pod
        image: 903479130308.dkr.ecr.us-east-1.amazonaws.com/hello-springboot:latest     # image Docker (dans ECR) / Utilisation de <TO_BE_REPLACED> pour passer l'image dynamiquement dans le pipeline 
        ports:
        - containerPort: 8080         # Port exposé par le conteneur (Spring Boot par défaut)