# voir https://kubernetes.io/docs/concepts/services-networking/service/

apiVersion: v1
kind: Service                     
metadata:
  name: hello-springboot-service 
spec:
  type: LoadBalancer              # Load Balancer AWS pour l’accès public
  selector:
    app: hello-springboot         
  ports:
    - protocol: TCP
      port: 80                    # Port ouvert publiquement (externe)
      targetPort: 8080           # Port du conteneur Spring Boot