replicaCount: 1

image:
  repository: ""        # injecté dynamiquement par ci-cd.yml
  pullPolicy: Always # Kubernetes cherchera toujours la dernière image
  tag: "latest"

service:
  type: ClusterIP # service accessible uniquement dans le cluster
  port: 8080

resources:
  limits: # ce que le pod ne dois jamais dépasser
    cpu: 500m
    memory: 512Mi
  requests: # ce que le pod demande au minimum pour fonctionner
    cpu: 250m
    memory: 256Mi

# détection d'erreur automatique
livenessProbe: # Kubernetes vérifie que l'app est encore vivante. Après plusieurs échec, redémarrage du pod.
  path: /actuator/health
  port: 8080

readinessProbe: # Kubernetes vérifie que l'app est prête à recevoir du trafic sinon elle n'est pas inclse dans le load balancing
  path: /actuator/health
  port: 8080