apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-public-deployment
  labels:
    app: frontend-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-public
  template:
    metadata:
      labels:
        app: frontend-public
    spec:
      containers:
        - name: frontend-public
          image: <TON_ECR_URL>/frontend-public:latest
          ports:
            - containerPort: 80